# .github/workflows/norminette.yml
name: norminette
on: [push, pull_request]

jobs:

  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
